//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nishtyachki.WcfCommunicator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfCommunicator.IWcfServiceCommunicator", CallbackContract=typeof(nishtyachki.WcfCommunicator.IWcfServiceCommunicatorCallback))]
    public interface IWcfServiceCommunicator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/InitUser", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/InitUserResponse")]
        void InitUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/InitUser", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/InitUserResponse")]
        System.Threading.Tasks.Task InitUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/TryStandInQueue", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/TryStandInQueueResponse")]
        bool TryStandInQueue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/TryStandInQueue", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/TryStandInQueueResponse")]
        System.Threading.Tasks.Task<bool> TryStandInQueueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/LeaveQueue", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/LeaveQueueResponse")]
        void LeaveQueue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/LeaveQueue", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/LeaveQueueResponse")]
        System.Threading.Tasks.Task LeaveQueueAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/AnswerForOfferToUse")]
        void AnswerForOfferToUse(bool willUse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/AnswerForOfferToUse")]
        System.Threading.Tasks.Task AnswerForOfferToUseAsync(bool willUse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/StopUseObj", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/StopUseObjResponse")]
        void StopUseObj();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/StopUseObj", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/StopUseObjResponse")]
        System.Threading.Tasks.Task StopUseObjAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/Disconnect", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/DisconnectResponse")]
        void Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/Disconnect", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/DisconnectResponse")]
        System.Threading.Tasks.Task DisconnectAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceCommunicatorCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/NotifyServerReady")]
        void NotifyServerReady();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/ShowMessage")]
        void ShowMessage(string text);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/StandInQueue")]
        void StandInQueue();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWcfServiceCommunicator/ShowPosition")]
        void ShowPosition(int position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/OfferToUseObj", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/OfferToUseObjResponse")]
        void OfferToUseObj();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/NotifyToUseObj", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/NotifyToUseObjResponse")]
        void NotifyToUseObj();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfServiceCommunicator/DroppedByServer", ReplyAction="http://tempuri.org/IWcfServiceCommunicator/DroppedByServerResponse")]
        void DroppedByServer(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceCommunicatorChannel : nishtyachki.WcfCommunicator.IWcfServiceCommunicator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceCommunicatorClient : System.ServiceModel.DuplexClientBase<nishtyachki.WcfCommunicator.IWcfServiceCommunicator>, nishtyachki.WcfCommunicator.IWcfServiceCommunicator {
        
        public WcfServiceCommunicatorClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WcfServiceCommunicatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WcfServiceCommunicatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceCommunicatorClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceCommunicatorClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void InitUser() {
            base.Channel.InitUser();
        }
        
        public System.Threading.Tasks.Task InitUserAsync() {
            return base.Channel.InitUserAsync();
        }
        
        public bool TryStandInQueue() {
            return base.Channel.TryStandInQueue();
        }
        
        public System.Threading.Tasks.Task<bool> TryStandInQueueAsync() {
            return base.Channel.TryStandInQueueAsync();
        }
        
        public void LeaveQueue() {
            base.Channel.LeaveQueue();
        }
        
        public System.Threading.Tasks.Task LeaveQueueAsync() {
            return base.Channel.LeaveQueueAsync();
        }
        
        public void AnswerForOfferToUse(bool willUse) {
            base.Channel.AnswerForOfferToUse(willUse);
        }
        
        public System.Threading.Tasks.Task AnswerForOfferToUseAsync(bool willUse) {
            return base.Channel.AnswerForOfferToUseAsync(willUse);
        }
        
        public void StopUseObj() {
            base.Channel.StopUseObj();
        }
        
        public System.Threading.Tasks.Task StopUseObjAsync() {
            return base.Channel.StopUseObjAsync();
        }
        
        public void Disconnect() {
            base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
    }
}
