//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp.AdminAppService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminAppService.IAdminAppService", CallbackContract=typeof(AdminApp.AdminAppService.IAdminAppServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IAdminAppService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/AddNishtiak", ReplyAction="http://tempuri.org/IAdminAppService/AddNishtiakResponse")]
        void AddNishtiak(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/AddNishtiak", ReplyAction="http://tempuri.org/IAdminAppService/AddNishtiakResponse")]
        System.Threading.Tasks.Task AddNishtiakAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/DeleteNishtiak", ReplyAction="http://tempuri.org/IAdminAppService/DeleteNishtiakResponse")]
        void DeleteNishtiak(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/DeleteNishtiak", ReplyAction="http://tempuri.org/IAdminAppService/DeleteNishtiakResponse")]
        System.Threading.Tasks.Task DeleteNishtiakAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/ChangeNishtiakState", ReplyAction="http://tempuri.org/IAdminAppService/ChangeNishtiakStateResponse")]
        void ChangeNishtiakState(string id, int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/ChangeNishtiakState", ReplyAction="http://tempuri.org/IAdminAppService/ChangeNishtiakStateResponse")]
        System.Threading.Tasks.Task ChangeNishtiakStateAsync(string id, int state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/DeleteUserByAdmin", ReplyAction="http://tempuri.org/IAdminAppService/DeleteUserByAdminResponse")]
        void DeleteUserByAdmin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/DeleteUserByAdmin", ReplyAction="http://tempuri.org/IAdminAppService/DeleteUserByAdminResponse")]
        System.Threading.Tasks.Task DeleteUserByAdminAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/SwitchQueueState", ReplyAction="http://tempuri.org/IAdminAppService/SwitchQueueStateResponse")]
        void SwitchQueueState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/SwitchQueueState", ReplyAction="http://tempuri.org/IAdminAppService/SwitchQueueStateResponse")]
        System.Threading.Tasks.Task SwitchQueueStateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/SendMsg", ReplyAction="http://tempuri.org/IAdminAppService/SendMsgResponse")]
        void SendMsg(string msg, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/SendMsg", ReplyAction="http://tempuri.org/IAdminAppService/SendMsgResponse")]
        System.Threading.Tasks.Task SendMsgAsync(string msg, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/ChangeUserRole", ReplyAction="http://tempuri.org/IAdminAppService/ChangeUserRoleResponse")]
        void ChangeUserRole(string id, int role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminAppService/ChangeUserRole", ReplyAction="http://tempuri.org/IAdminAppService/ChangeUserRoleResponse")]
        System.Threading.Tasks.Task ChangeUserRoleAsync(string id, int role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminAppServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminAppService/UpdateQueue")]
        void UpdateQueue();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAdminAppService/UpdateNishtiachok")]
        void UpdateNishtiachok();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminAppServiceChannel : AdminApp.AdminAppService.IAdminAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminAppServiceClient : System.ServiceModel.DuplexClientBase<AdminApp.AdminAppService.IAdminAppService>, AdminApp.AdminAppService.IAdminAppService {
        
        public AdminAppServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AdminAppServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AdminAppServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAppServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AdminAppServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void AddNishtiak(string id) {
            base.Channel.AddNishtiak(id);
        }
        
        public System.Threading.Tasks.Task AddNishtiakAsync(string id) {
            return base.Channel.AddNishtiakAsync(id);
        }
        
        public void DeleteNishtiak(string id) {
            base.Channel.DeleteNishtiak(id);
        }
        
        public System.Threading.Tasks.Task DeleteNishtiakAsync(string id) {
            return base.Channel.DeleteNishtiakAsync(id);
        }
        
        public void ChangeNishtiakState(string id, int state) {
            base.Channel.ChangeNishtiakState(id, state);
        }
        
        public System.Threading.Tasks.Task ChangeNishtiakStateAsync(string id, int state) {
            return base.Channel.ChangeNishtiakStateAsync(id, state);
        }
        
        public void DeleteUserByAdmin(string id) {
            base.Channel.DeleteUserByAdmin(id);
        }
        
        public System.Threading.Tasks.Task DeleteUserByAdminAsync(string id) {
            return base.Channel.DeleteUserByAdminAsync(id);
        }
        
        public void SwitchQueueState() {
            base.Channel.SwitchQueueState();
        }
        
        public System.Threading.Tasks.Task SwitchQueueStateAsync() {
            return base.Channel.SwitchQueueStateAsync();
        }
        
        public void SendMsg(string msg, string id) {
            base.Channel.SendMsg(msg, id);
        }
        
        public System.Threading.Tasks.Task SendMsgAsync(string msg, string id) {
            return base.Channel.SendMsgAsync(msg, id);
        }
        
        public void ChangeUserRole(string id, int role) {
            base.Channel.ChangeUserRole(id, role);
        }
        
        public System.Threading.Tasks.Task ChangeUserRoleAsync(string id, int role) {
            return base.Channel.ChangeUserRoleAsync(id, role);
        }
    }
}
