//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvvmUserApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MvvmUserApp.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancelEnabled {
            get {
                return ResourceManager.GetString("BtnCancelEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enqueue.
        /// </summary>
        internal static string BtnEnqueuEneble {
            get {
                return ResourceManager.GetString("BtnEnqueuEneble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BtnNoEnabled {
            get {
                return ResourceManager.GetString("BtnNoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BtnYesEnabled {
            get {
                return ResourceManager.GetString("BtnYesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages from server:.
        /// </summary>
        internal static string LblMsgText {
            get {
                return ResourceManager.GetString("LblMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from server..
        /// </summary>
        internal static string MessageBoxHead {
            get {
                return ResourceManager.GetString("MessageBoxHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use some nishtiak?.
        /// </summary>
        internal static string OfferToUse {
            get {
                return ResourceManager.GetString("OfferToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are {0} in queue for nishtiak, wait please..
        /// </summary>
        internal static string PositionInQueue {
            get {
                return ResourceManager.GetString("PositionInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can stay in queue for some nihtiaks..
        /// </summary>
        internal static string ServerReady {
            get {
                return ResourceManager.GetString("ServerReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait initialization..
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait free nishtiak..
        /// </summary>
        internal static string StayInQueue {
            get {
                return ResourceManager.GetString("StayInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is in trey..
        /// </summary>
        internal static string String1TreyWindowTexTreyWindowText {
            get {
                return ResourceManager.GetString("String1TreyWindowTexTreyWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is in trey!.
        /// </summary>
        internal static string TreyWindowText {
            get {
                return ResourceManager.GetString("TreyWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using nishtiak! Come and get it!.
        /// </summary>
        internal static string UseNishtiak {
            get {
                return ResourceManager.GetString("UseNishtiak", resourceCulture);
            }
        }
    }
}
